//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfPaymentsSiva.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clientes()
        {
            this.CuentasTelepeajes = new HashSet<CuentasTelepeajes>();
        }
    
        public long Id { get; set; }
        public string NumCliente { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string EmailCliente { get; set; }
        public string AddressCliente { get; set; }
        public string PhoneCliente { get; set; }
        public bool StatusCliente { get; set; }
        public System.DateTime DateTCliente { get; set; }
        public string IdCajero { get; set; }
        public string Empresa { get; set; }
        public string CP { get; set; }
        public string Pais { get; set; }
        public string City { get; set; }
        public string Departamento { get; set; }
        public string NIT { get; set; }
        public string PhoneOffice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuentasTelepeajes> CuentasTelepeajes { get; set; }
    }
}
