//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfPaymentsSiva.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CortesCajeroes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CortesCajeroes()
        {
            this.OperacionesCajeroes = new HashSet<OperacionesCajeroes>();
        }
    
        public long Id { get; set; }
        public string NumCorte { get; set; }
        public System.DateTime DateTApertura { get; set; }
        public Nullable<System.DateTime> DateTCierre { get; set; }
        public Nullable<double> MontoTotal { get; set; }
        public string Comentario { get; set; }
        public string IdCajero { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperacionesCajeroes> OperacionesCajeroes { get; set; }
    }
}
