//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfPaymentsSiva.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historico
    {
        public int Id { get; set; }
        public string Tag { get; set; }
        public string Delegacion { get; set; }
        public string Plaza { get; set; }
        public string Cuerpo { get; set; }
        public string Carril { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Clase { get; set; }
        public string Evento { get; set; }
        public double Saldo { get; set; }
        public string Operador { get; set; }
        public string SaldoAnterior { get; set; }
        public string SaldoActualizado { get; set; }
        public string NumeroCuenta { get; set; }
        public string TipoCuenta { get; set; }
    }
}
