//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfPaymentsSiva.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoricoListas
    {
        public long Id { get; set; }
        public string Extension { get; set; }
        public string Tamaño { get; set; }
        public System.DateTime Fecha_Creacion { get; set; }
        public string Tipo { get; set; }
    }
}
