//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfPaymentsSiva.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListaNegra
    {
        public long Id { get; set; }
        public string Tipo { get; set; }
        public string Numero { get; set; }
        public string Observacion { get; set; }
        public Nullable<double> SaldoAnterior { get; set; }
        public System.DateTime Date { get; set; }
        public string IdCajero { get; set; }
        public string Clase { get; set; }
        public string NumCliente { get; set; }
        public string NumCuenta { get; set; }
    }
}
