//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfPaymentsSiva.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperacionesCajeroes
    {
        public long Id { get; set; }
        public string Concepto { get; set; }
        public string TipoPago { get; set; }
        public Nullable<double> Monto { get; set; }
        public System.DateTime DateTOperacion { get; set; }
        public long CorteId { get; set; }
        public string Numero { get; set; }
        public string Tipo { get; set; }
        public Nullable<double> CobroTag { get; set; }
        public string NoReferencia { get; set; }
        public bool StatusCancelacion { get; set; }
    
        public virtual CortesCajeroes CortesCajeroes { get; set; }
    }
}
