//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfPaymentsSiva.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperacionesSerBIpagos
    {
        public long Id { get; set; }
        public string NumAutoriProveedor { get; set; }
        public string NumAutoriBanco { get; set; }
        public Nullable<double> SaldoAnterior { get; set; }
        public Nullable<double> SaldoModificar { get; set; }
        public Nullable<double> SaldoActual { get; set; }
        public bool StatusOperacion { get; set; }
        public System.DateTime DateTOpSerBI { get; set; }
        public string Numero { get; set; }
        public string NoReferencia { get; set; }
        public string Tipo { get; set; }
        public string Concepto { get; set; }
    }
}
