//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfPaymentsSiva.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametrizables
    {
        public int id { get; set; }
        public string origen { get; set; }
        public string destino { get; set; }
        public int extension { get; set; }
        public string destinoresidente { get; set; }
        public short cruzes { get; set; }
        public short minutos { get; set; }
    }
}
