//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfPaymentsSiva.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tags
    {
        public long Id { get; set; }
        public string NumTag { get; set; }
        public string SaldoTag { get; set; }
        public bool StatusTag { get; set; }
        public bool StatusResidente { get; set; }
        public System.DateTime DateTTag { get; set; }
        public long CuentaId { get; set; }
        public string IdCajero { get; set; }
    
        public virtual CuentasTelepeajes CuentasTelepeajes { get; set; }
    }
}
